<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuites_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8ee07662-f73e-4d0b-868c-597945ca0942</testSuiteGuid>
   <testCaseLink>
      <guid>b87a482f-08d5-4428-b479-fd0271a16fb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common_TC/Login/TC_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4be3adaa-e774-41bb-b591-506d5cee6cc0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/credentials</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4be3adaa-e774-41bb-b591-506d5cee6cc0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>29e3ec01-f527-4653-9a66-9d60e7ab0595</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4be3adaa-e774-41bb-b591-506d5cee6cc0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>0b68a9eb-0411-4bf4-b2ee-7480149eae53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4be3adaa-e774-41bb-b591-506d5cee6cc0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>3b8ee43e-2a8c-4c52-8a7c-c1bb00260e30</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
